unravel:
  clusters: tnode28-HDP315-TLS-Kerb-Ranger, tnode3-CDH633-TLS-Kerb-Sentry
  impala_clusters: CM-tnode1-Unravel-tnode3-impala
  hbase_clusters: HDPab722, CM-tnode1-Unravel-tnode3-impala
  mapreduce_clusters: tnode3-CDH633-TLS-kerb-Sentry

aws:
  bucket_name: unravel-automation-files